[profile.default]
src = ["contracts", "lib/v2-core/contracts"]
remappings = [
  "@uniswap/v2-core/=lib/v2-core/",
  "@uniswap/lib/=lib/lib/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

solc_version = '0.8.28'

# Build optimization settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Security settings
deny_warnings = false
fuzz_runs = 10000

# Test settings
fs_permissions = [{ access = "read", path = "./test/"}]

[profile.optimized]
inherits = "default"
optimizer = true
optimizer_runs = 1000000
via_ir = true

[profile.security]
inherits = "default"
deny_warnings = true
fuzz_runs = 50000

[profile.production]
inherits = "optimized"
deny_warnings = true
fuzz_runs = 100000
