name: Optimized CI/CD Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  # Foundry and Smart Contract Tests
  foundry:
    name: Foundry Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: yarn

      - name: Cache Foundry dependencies
        uses: actions/cache@v2
        with:
          path: ~/.foundry/cache
          key: foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            foundry-

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Foundry fmt
        run: forge fmt --check

      - name: Build contracts (CI profile)
        run: forge build --build-info --sizes

      - name: Run tests
        run: forge test --gas-report

      - name: Run fuzz tests
        run: forge test --fuzz-runs 256
        continue-on-error: true

      - name: Run security tests
        run: forge test --profile security
        continue-on-error: true

  # Node.js and TypeScript Tests
  nodejs:
    name: Node.js Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn lint:all

      - name: Run TypeScript tests
        run: yarn test

      - name: Build size analysis
        run: yarn build:size
        continue-on-error: true

      - name: Security audit
        run: yarn security:audit
        continue-on-error: true

  # Agent Dashboard Frontend Build
  frontend:
    name: Frontend Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: |
          cd standalone/agent-dashboard/frontend
          yarn install --frozen-lockfile
          yarn build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: standalone/agent-dashboard/frontend/build/
          retention-days: 30

  # Multi-chain deployment check
  deploy-check:
    name: Deployment Check
    runs-on: ubuntu-22.04
    needs: [foundry, nodejs, frontend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Foundry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.foundry/cache
          key: foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            foundry-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build:production
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          # Ensure DEPLOYER_PRIVATE_KEY is set in repository secrets
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/
            build/
            standalone/agent-dashboard/frontend/build/
          retention-days: 30
